using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonAssertions;

/// <summary>
/// Internal mirror of the RFC 7807 ProblemDetails wire shape. Deliberately NOT a reference to
/// <c>Microsoft.AspNetCore.Mvc.ProblemDetails</c>: taking that dep would pull
/// <c>Microsoft.AspNetCore.Mvc.Abstractions</c> (Apache 2.0) into the package's transitive
/// dependencies, weakening the family's MIT-only consumer-facing posture and adding an
/// ASP.NET-specific reference for consumers doing Refit / gRPC-Web / raw <c>HttpClient</c>
/// testing.
/// </summary>
/// <remarks>
/// <para>STJ deserialization is structural-by-property-name, not by type-identity: a server
/// that serializes <c>Microsoft.AspNetCore.Mvc.ProblemDetails</c> emits the property names
/// <c>type</c>, <c>title</c>, <c>status</c>, <c>detail</c>, <c>instance</c> which match this
/// mirror's <see cref="JsonPropertyNameAttribute"/>-annotated members; the deserializer reads
/// the JSON into this mirror correctly regardless of the server-side type.</para>
/// <para>The mirror is <see langword="internal"/>; consumers see only the
/// <c>MatchesProblemDetails(...)</c> / <c>MatchesValidationProblemDetails(...)</c> methods.
/// Per the family's strategic invariant, future fields can be added to the mirror without
/// API-surface breakage.</para>
/// <para>RFC 7807 was published 2016 and is stable; the mirror's drift risk is bounded.
/// The type is non-sealed so <see cref="ValidationProblemDetailsMirror"/> can derive from it.</para>
/// <para>Properties use <c>get; set;</c> (not <c>init</c>) deliberately: STJ source-gen
/// synthesizes a deserialization constructor when any property uses <c>init</c>, and
/// <see cref="JsonExtensionDataAttribute"/> cannot bind to a constructor parameter. Object-
/// initializer-based deserialization (via <c>set</c>) keeps the extension-member capture path
/// intact. The mirror is internal, so the <c>init</c>-vs-<c>set</c> distinction is purely an
/// internal-style choice.</para>
/// </remarks>
[SuppressMessage(
    "MeziantouAnalyzer",
    "MA0182:Unused internal type",
    Justification = "Consumed by the MatchesProblemDetails assertion path and by the internal STJ source-gen context in the same assembly.")]
internal class ProblemDetailsMirror
{
    /// <summary>The URI reference identifying the problem type (RFC 7807 §3.1).</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>A short, human-readable summary of the problem (RFC 7807 §3.1).</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>The HTTP status code generated by the origin server (RFC 7807 §3.1).</summary>
    [JsonPropertyName("status")]
    public int? Status { get; set; }

    /// <summary>A human-readable explanation specific to this occurrence (RFC 7807 §3.1).</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }

    /// <summary>A URI reference identifying the specific occurrence of the problem
    /// (RFC 7807 §3.1).</summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; set; }

    /// <summary>RFC 7807 §3.2 problem-type extension members captured into a dictionary so the
    /// mirror tolerates server-side custom fields without losing them. Captured in v0.3.0 but
    /// not asserted by <c>MatchesProblemDetails</c>'s current surface; a future
    /// <c>WithExtension(name, value)</c> chain method may expose the assertion surface (tracked
    /// as a v0.3.1 / v0.4.0 candidate). The capture-into-dictionary behaviour means an
    /// extension-member-bearing response does not lose its extension data on deserialization.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extensions { get; set; }
}
