using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace JsonAssertions;

/// <summary>
/// Internal mirror of the RFC 7807 ProblemDetails wire shape. Deliberately NOT a reference to
/// <c>Microsoft.AspNetCore.Mvc.ProblemDetails</c>: taking that dep would pull
/// <c>Microsoft.AspNetCore.Mvc.Abstractions</c> (Apache 2.0) into the package's transitive
/// dependencies, weakening the family's MIT-only consumer-facing posture and adding an
/// ASP.NET-specific reference for consumers doing Refit / gRPC-Web / raw <c>HttpClient</c>
/// testing.
/// </summary>
/// <remarks>
/// <para>STJ deserialization is structural-by-property-name, not by type-identity: a server
/// that serializes <c>Microsoft.AspNetCore.Mvc.ProblemDetails</c> emits the property names
/// <c>type</c>, <c>title</c>, <c>status</c>, <c>detail</c>, <c>instance</c> which match this
/// mirror's <see cref="JsonPropertyNameAttribute"/>-annotated members; the deserializer reads
/// the JSON into this mirror correctly regardless of the server-side type.</para>
/// <para>The mirror is <see langword="internal"/>; consumers see only the
/// <c>MatchesProblemDetails(...)</c> / <c>MatchesValidationProblemDetails(...)</c> methods.
/// Per the family's strategic invariant, future fields can be added to the mirror without
/// API-surface breakage.</para>
/// <para>RFC 7807 was published 2016 and is stable; the mirror's drift risk is bounded.
/// The type is non-sealed so <see cref="ValidationProblemDetailsMirror"/> can derive from it.</para>
/// </remarks>
[SuppressMessage(
    "MeziantouAnalyzer",
    "MA0182:Unused internal type",
    Justification = "Consumed by the MatchesProblemDetails assertion path and by the internal STJ source-gen context in the same assembly.")]
internal class ProblemDetailsMirror
{
    /// <summary>The URI reference identifying the problem type (RFC 7807 §3.1).</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>A short, human-readable summary of the problem (RFC 7807 §3.1).</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>The HTTP status code generated by the origin server (RFC 7807 §3.1).</summary>
    [JsonPropertyName("status")]
    public int? Status { get; init; }

    /// <summary>A human-readable explanation specific to this occurrence (RFC 7807 §3.1).</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; init; }

    /// <summary>A URI reference identifying the specific occurrence of the problem
    /// (RFC 7807 §3.1).</summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; init; }

    // Note: RFC 7807 §3.2 problem-type extension members are not captured in v0.3.0. A future
    // [JsonExtensionData] property + .WithExtension(name, value) chain method may be added in
    // v0.3.1 / v0.4.0 if consumer demand surfaces. Adding [JsonExtensionData] today triggers
    // a STJ source-gen "cannot bind with a parameter in the deserialization constructor"
    // error when combined with init-only properties; resolving that is part of the v0.3.1
    // design work for extensions support, not v0.3.0 scope.
}
